---
name: release

on:
  pull_request:
  release:
    types: [published]

jobs:
  update-manifest:
    name: Update manifest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Generate next version
        id: version
        uses: ietf-tools/semver-action@v1
        with:
          token: ${{ github.token }}
          branch: >-
            ${{
              github.head_ref
              || github.event.repository.default_branch
            }}

      - name: Set version in manifest and commit that
        uses: maxgfr/github-change-json@v0.0.26
        env:
          GITHUB_HEAD_REF: ${{ github.event.repository.default_branch }}
          GITHUB_REF: ${{ github.event.repository.default_branch }}
        with:
          key: version
          value: ${{ steps.version.outputs.nextStrict }}
          path: custom_components/gs_alarm/manifest.json
          commit: true
