---
name: release

on:
  release:
    types: [published]

jobs:
  update-manifest:
    name: Update manifest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
        with:
          # No history needed
          fetch-depth: 1
          # Git will use deploy SSH key, mostly to push to default branch being
          # protected
          ssh-key: ${{ secrets.DEPLOY_KEY }}

      - name: Set version in manifest and commit that
        uses: maxgfr/github-change-json@v0.0.26
        with:
          key: version
          value: ${{ github.event.release.tag_name }}
          path: custom_components/gs_alarm/manifest.json

      - name: Commit updated manifest
        run: |
          git config --local user.email \
            "github-actions[bot]@users.noreply.github.com"
          git config --local user.name \
            "github-actions[bot]"
          git add custom_components/gs_alarm/manifest.json
          git commit -m "Updating version in 'manifest.json'"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          # SSH (deploy) key allows to bypass branch protection on default
          # branch
          ssh: true
          branch: ${{ github.event.repository.default_branch }}
