---
name: release

on:
  pull_request:
  release:
    types: [published]

jobs:
  update-manifest:
    name: Update manifest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ssh-key: ${{ secrets.DEPLOY_KEY }}

      - name: Generate next version
        id: version
        uses: ietf-tools/semver-action@v1
        with:
          token: ${{ github.token }}
          branch: >-
            ${{
              github.head_ref
              || github.event.repository.default_branch
            }}

      - name: Set version in manifest and commit that
        uses: maxgfr/github-change-json@v0.0.26
        with:
          key: version
          value: ${{ steps.version.outputs.nextStrict }}
          path: custom_components/gs_alarm/manifest.json

      - name: Commit updated manifest
        uses: actions4git/add-commit-push@v1
        with:
          add-pathspec: custom_components/gs_alarm/manifest.json 
          push-refspec: ${{ github.event.repository.default_branch }}
