---
name: release

on:
  pull_request:
  release:
    types: [published]

jobs:
  update-manifest:
    name: Update manifest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          fetch-tags: true

      - name: Generate next version
        id: version
        uses: gandarez/semver-action@v2.0.0
        with:
          branching_model: trunk-based

      - name: Set version in manifest and commit that
        uses: maxgfr/github-change-json@v0.0.26
        with:
          key: version
          value: ${{ steps.version.outputs.semver_tag }}
          path: custom_components/gs_alarm/manifest.json
          commit: true
