---
name: release

on:
  release:
    types: [published]

jobs:
  update-manifest:
    name: Update manifest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get version
        id: version
        uses: home-assistant/actions/helpers/version@master

      - name: Set version in manifest and commit that
        uses: maxgfr/github-change-json@v0.0.26
        with:
          key: version
          value: ${{ steps.version.outputs.version }}
          path: custom_components/gs_alarm/manifest.json
          commit: true
